### PR TITLE
Remove res.body.cancel

### PR DESCRIPTION
**Pull request by juliantoledo**
@andreban Can we just remove this? I cannot find a problem if I remove it.

### CODE REVIEW

**Comment by andreban** [comment]
This was part of the code when H2 support was added (https://github.com/GoogleChromeLabs/gulliver/commit/b04f6867bebd0f325cea2cb731fc3a440331b53a). I changed from res.text(), which would fully consume the content, to res.body.cancel() that actually cancels the stream.

Not sure why res.text() was added initially. Maybe to avoid leaving pending streams?

**Comment by juliantoledo** [comment]
Yes, I most be because of the pending streams.

**Comment by juliantoledo** [comment]
@andreban the spdy workaround is not needed anymore

**Comment by andreban** [comment]
Awesome! thanks!

**Pull request merged**
