### PR TITLE
Adds a RSS ouput for the feed

### PR DESCRIPTION
**Pull request by andreban**
This adds an RSS feed, as requested on #463. There are 2 things we need to look: 
- Do we need an API_KEY for the feed? 
- Also, it seems we always deliver the entire list of PWAs. Maybe we could add parameters to paginate?

### CODE REVIEW

**Comment by juliantoledo** [comment]
Very fast PR!
- I think we should not ask for the API_KEY for the RSS.
- Yes, pagination could be good as optional and it should be sorted by 'newest'

Thank you.

**Comment by PaulKinlan** [comment]
This is looking awesome.  One extra thing, we should add in a <link rel=alternate> on main page that points directly to the RSS feed. This will help people add it to their feed readers and hopefully help increase discovery. Selfishly, I'm about to deploy a site that would link to this feed :)

**Comment by PaulKinlan** [comment]
Maybe it's not for this PR,

But I would love us to flesh out the content/description for each PWA, so that it includes a link to Gulliver, a Link to the start url so that they can try it out, and also include a summary of all that we know (manifest name, description, icon, speedscores,lighthouse etc.)

**Comment by juliantoledo** [comment]
I will continue in another PR.

**Pull request merged**
