### PR TITLE
[WIP]Adds an 'Installable' tab

### PR DESCRIPTION
**Pull request by andreban**
- Currently, using lighthouseScore >= 90 as a proxy for
  installability
- Moving tabs to paths instead of query string (eg: /?sort=newest
  to /pwas/newest)

### CODE REVIEW

**Comment by andreban** [comment]
Still needs work on the UI. Adding that to the next commit.

**Comment by andreban** [comment]
Related to #477

**Comment by juliantoledo** [comment]
LGTM, just one question.
Should Installable be the default? Currently http://localhost:8080/ points to newest.

**Comment by andreban** [comment]
Yes, the plan is to make them the default. We can deploy the 1st version with the installable tab hidden, so we can make sure that the lighthouseScore >= 90 makes sense. Once we have that, we make it the default. WDYT?

**Comment by juliantoledo** [comment]
SGTM

I can surface the installable flag from the LH reports.

**Pull request merged**
